function stress_str = writeStressRec(stresses)
    stress_str = sprintf("TENSORS Stress float \n");
    for a = 1:size(stresses,2)
        stress_str = stress_str + sprintf("%.9f %.9f %.9f \n"+...
                                          "%.9f %.9f %.9f \n"+...
                                          "%.9f %.9f %.9f \n\n",...
                            stresses(1,a),stresses(4,a),stresses(5,a),...
                            stresses(4,a),stresses(2,a),stresses(6,a),...
                            stresses(5,a),stresses(6,a),stresses(3,a));
    end
end